parameters:
  # UUID for public network (find with neutron net-list)
  public_network: 

  # PostgreSQL IaaS instance
  flavor: 
  image: 
  key_name: 

  # Ticketmonster application
  openshift_domain: 
  openshift_name: 
